[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "slackipy"
author = "Dhananjay"
author-email = "dhananjay@ranium.in"
classifiers = ["License :: OSI Approved :: MIT License"]

